# Generated by Django 3.0.5 on 2020-04-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
